In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

# Plot settings
plt.rcParams["figure.figsize"] = (10, 6)
sns.set_style("whitegrid")

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
DATA_PATH = "../data/processed/final_processed_data.csv"

df = pd.read_csv(DATA_PATH)

print("Processed dataset loaded successfully.")
print("Shape:", df.shape)

Processed dataset loaded successfully.
Shape: (52930, 25)

In [3]:
df.head()

   TransactionId  UserId  VisitYear  VisitMonth  VisitMode  AttractionId  Rating  ContinentId  RegionId  CountryId  CityId  AttractionCityId  AttractionTypeId                      Attraction                        AttractionAddress           AttractionType  VisitModeId  CityId_city CityName  CountryId_city         Country  RegionId_country            Region  ContinentId_region Continent
0              3   70456       2022          10          2           640       5            5        21        163  4341.0                 1                63  Sacred Monkey Forest Sanctuary  Jl. Monkey Forest, Ubud 80571 Indonesia  Nature & Wildlife Areas          NaN            1   Douala               1  United Kingdom                21    Western Europe                   5    Europe
1              8    7567       2022          10          4           640       5            2         8         48   464.0                 1                63  Sacred Monkey Forest Sanctuary  Jl. Monkey Forest, Ubud 80571 Indonesia  Nature & Wildlife Areas          NaN            1   Douala               1          Canada                 8  Northern America                   2   America
2              9   79069       2022          10          3           640       5            2         9         54   774.0                 1                63  Sacred Monkey Forest Sanctuary  Jl. Monkey Forest, Ubud 80571 Indonesia  Nature & Wildlife Areas          NaN            1   Douala               1          Brazil                 9     South America                   2   America
3             10   31019       2022          10          3           640       3            5        17        135   583.0                 1                63  Sacred Monkey Forest Sanctuary  Jl. Monkey Forest, Ubud 80571 Indonesia  Nature & Wildlife Areas          NaN            1   Douala               1     Switzerland                17    Central Europe                   5    Europe
4             15   43611       2022          10          2           640       3            5        21        163  1396.0                 1                63  Sacred Monkey Forest Sanctuary  Jl. Monkey Forest, Ubud 80571 Indonesia  Nature & Wildlife Areas          NaN            1   Douala               1  United Kingdom                21    Western Europe                   5    Europe

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52930 entries, 0 to 52929
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TransactionId       52930 non-null  int64
 1   UserId              52930 non-null  int64
 2   VisitYear           52930 non-null  int64
 3   VisitMonth          52930 non-null  int64
 4   VisitMode           52930 non-null  int64
 5   AttractionId        52930 non-null  int64
 6   Rating              52930 non-null  int64
 7   ContinentId         52930 non-null  int64
 8   RegionId            52930 non-null  int64
 9   CountryId           52930 non-null  int64
 10  CityId              52930 non-null  float64
 11  AttractionCityId    52930 non-null  int64
 12  AttractionTypeId    52930 non-null  int64
 13  Attraction          52930 non-null  str
 14  AttractionAddress   52930 non-null  str
 15  AttractionType      52930 non-null  str
 16  VisitModeId         0 non-null      float64
 17  CityId_city         52930 non-null  int64
 18  CityName            52930 non-null  str
 19  CountryId_city      52930 non-null  int64
 20  Country             52930 non-null  str
 21  RegionId_country    52930 non-null  int64
 22  Region              52930 non-null  str
 23  ContinentId_region  52930 non-null  int64
 24  Continent           52930 non-null  str
dtypes: float64(2), int64(16), str(7)
memory usage: 15.6 MB

In [5]:
df.describe(include="all").T

                      count unique                                      top   freq          mean           std     min       25%      50%        75%       max
TransactionId       52930.0    NaN                                      NaN    NaN  70415.130474  66299.514206     3.0  19646.25  42770.5  105638.75  211241.0
UserId              52930.0    NaN                                      NaN    NaN  45024.522596  25073.062199    14.0   23470.0  45533.5    66667.0   88190.0
VisitYear           52930.0    NaN                                      NaN    NaN   2016.351899      1.732926  2013.0    2015.0   2016.0     2018.0    2022.0
VisitMonth          52930.0    NaN                                      NaN    NaN        6.6331      3.392979     1.0       4.0      7.0        9.0      12.0
VisitMode           52930.0    NaN                                      NaN    NaN      2.945759      1.000683     1.0       2.0      3.0        4.0       5.0
AttractionId        52930.0    NaN                                      NaN    NaN    759.663782    210.716111   369.0     640.0    737.0      841.0    1297.0
Rating              52930.0    NaN                                      NaN    NaN      4.157699      0.970543     1.0       4.0      4.0        5.0       5.0
ContinentId         52930.0    NaN                                      NaN    NaN      3.592877      1.075526     1.0       3.0      4.0        5.0       5.0
RegionId            52930.0    NaN                                      NaN    NaN     14.524353      4.186649     0.0      13.0     15.0       17.0      21.0
CountryId           52930.0    NaN                                      NaN    NaN    106.297657     35.738949     1.0      93.0    109.0      121.0     164.0
CityId              52930.0    NaN                                      NaN    NaN   3398.096335   2325.898756     1.0    1434.0   3156.0     4940.0    9142.0
AttractionCityId    52930.0    NaN                                      NaN    NaN      1.277555      0.680015     1.0       1.0      1.0        1.0       3.0
AttractionTypeId    52930.0    NaN                                      NaN    NaN     58.919838      28.34428     2.0      34.0     63.0       76.0      93.0
Attraction            52930     30           Sacred Monkey Forest Sanctuary  13198           NaN           NaN     NaN       NaN      NaN        NaN       NaN
AttractionAddress     52930     25  Jl. Monkey Forest, Ubud 80571 Indonesia  13198           NaN           NaN     NaN       NaN      NaN        NaN       NaN
AttractionType        52930     17                  Nature & Wildlife Areas  13251           NaN           NaN     NaN       NaN      NaN        NaN       NaN
VisitModeId             0.0    NaN                                      NaN    NaN           NaN           NaN     NaN       NaN      NaN        NaN       NaN
CityId_city         52930.0    NaN                                      NaN    NaN      1.277555      0.680015     1.0       1.0      1.0        1.0       3.0
CityName              52930      3                                   Douala  45170           NaN           NaN     NaN       NaN      NaN        NaN       NaN
CountryId_city      52930.0    NaN                                      NaN    NaN      1.130947      0.337345     1.0       1.0      1.0        1.0       2.0
Country               52930    153                                Australia  13322           NaN           NaN     NaN       NaN      NaN        NaN       NaN
RegionId_country    52930.0    NaN                                      NaN    NaN     14.524202      4.186596     0.0      13.0     15.0       17.0      21.0
Region                52930     22                                Australia  13322           NaN           NaN     NaN       NaN      NaN        NaN       NaN
ContinentId_region  52930.0    NaN                                      NaN    NaN      3.590761      1.078933     0.0       3.0      4.0        5.0       5.0
Continent             52930      5                                     Asia  15693           NaN           NaN     NaN       NaN      NaN        NaN       NaN

In [6]:
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print("Columns with missing values:")
display(missing)

Columns with missing values:

VisitModeId    52930
dtype: int64